### ISSUE TITLE
User pub dies but is still subscribed

### ISSUE THREAD

**Issue by tarrencev** [ionorg/ion#178] opened 2020-05-13 18:53 UTC
I'm seeing an intermittent issue when a users pub seems to die, they stop streaming video/audio, but their subs are still active, so they can see everyone else in the room. When this happens, their stream freezes for everyone else but they can still hear everyone else. It seems to happen more frequently with bad internet (lossy/slow).

I've seen this issue brought up a bit is slack too.

**Comment by jbrady42** [comment] 2020-05-14 14:26
This is probably something we can handle client side. If the client ICE state goes to failed, but you are still connected via websocket, then send unpublish, then republish the stream.

**Comment by tarrencev** [comment] 2020-05-14 14:30
Interesting. What could cause ICE to go into a failed state?

**Comment by jbrady42** [comment] 2020-05-14 15:12
My thought here was the rtc connection is less robust than the tcp websocket, so it may drop while the ws client was still connected. I have tested with the load tool and dropped connection at the network level and observed the failed/disconnected ice state, but you get a logoff/unpublish from the ws and biz layer. Still not completely certain it is the root cause here. Need to do more testing and see what happens when the rtc connection drops wile leaving the websocket open.

**Comment by jbrady42** [comment] 2020-05-14 15:17
Or maybe network condition/delay is causing the SFU to time out the pub and closing the router. Either way we can attempt to republish from the client side if we know there is an issue.

**Comment by tarrencev** [comment] 2020-05-14 15:22
It is also interesting that the sub rtc connections remain active. I've also seen an instance when the subs die but pub is active (everyone can see/hear user but they dont see/hear anyone else)

**Comment by jbrady42** [comment] 2020-05-14 15:28
I think the subs active when pub dies case was related to the mediakey fix that just went in. But I have experienced the dropped pub that is still in the room and getting subs. We thought someone dropped, but it was only their stream and they were still receiving everyone else.

**Comment by tarrencev** [comment] 2020-05-14 15:29
yup that is the same scenario i have experience

**Closed as completed** 2020-12-06 14:20 UTC
Labels: bug
